EVALUATE
VAR matchScore =
    SUMMARIZE(
        'Matches',
        'Matches'[Match Id],
        'Matches'[Match Name],
        'Matches'[Home Team Score],
        'Matches'[Away Team Score]
    )
VAR sameScore =
    FILTER(
        matchScore,
        'Matches'[Home Team Score] = 'Matches'[Away Team Score]
    )
VAR topSameScore =
    TOPN( 1, sameScore, 'Matches'[Home Team Score], DESC )
VAR topSameScoreList =
    CONCATENATEX(
        topSameScore,
        'Matches'[Match Name],
        ", ",
        'Matches'[Match Name]
    )
RETURN
    { topSameScoreList }